### ISSUE TITLE
Error : "The value provided ('XX') could not be validated in the absence of a terminology server" and difficulties to configure a TxServer

### ISSUE THREAD

**Issue by TristanKEREVAL** [ahdis/matchbox#140]
We are using a Matchbox v3.2.1 Instance, we have this message " The value provided ('kg') could not be validated in the absence of a terminology server /Observation/value/ofType(Quantity)/code " when we try to validate a Observation resource's instance.
The value provided is fixed in the StructureDefinition. So we tried to add a terminology server by using the matchbox GUI, and with every TxServer that we use we get this message : 
Validation for profile https://interop.esante.gouv.fr/ig/fhir/mesures/StructureDefinition/mesures-fr-observation-body-weight not supported by this server, but additional ig's could be configured. 

We tried the same validation on the public test server (https://test.ahdis.ch/matchboxv3/#/validate), which also include the package of this SD and the message was not in the result.

Maybe we did not understand how the TxServer should be used but it looks like it is using the server provided in the TxServer field, as the validation server.

Is this a normal behaviour for the system ?

Thank you,
Tristan RIEU.

**Comment by oliveregger** [comment]
>Validation for profile https://interop.esante.gouv.fr/ig/fhir/mesures/StructureDefinition/mesures-fr-observation-body-weight not supported by this server, but additional ig's could be configured.

This error message indicates that the package for this implementation guide has not been found for this canonical url. Maybe update to the lastest version, we had noticed this problem. If you update to a new version you might start with a fresh
database.

>Maybe we did not understand how the TxServer should be used but it looks like it is using the server provided in the TxServer field, as the validation server.

See https://ahdis.github.io/matchbox/validation/

1. provide it during matchbox startup in application.yml (displayIssuesAreWarnings is only available since 3.4.3)

```yaml
matchbox:
  fhir:
    context:
      fhirVersion: 4.0.1
      txServer: http://tx.fhir.org
      displayIssuesAreWarnings: true
```

note: http://tx.fhir.org is the only server currently woking with matchbox 

2. provide it a request parameter during the matchbox validation call (changes in the GUI validation do not have an effect on matchbox API). you should see in the OperationOutcome what parameters have been used for the validation.  

>Is this a normal behaviour for the system ?
yes. you should be able to use it with a terminology server or not.

**Comment by oliveregger** [comment]
@TristanKEREVAL could you solve your issue with the txServer? can we close the issue?

**Comment by TristanKEREVAL** [comment]
The package containing the tested SD's is installed locally on the server so it should know the canonial URL. 
When we configure the txServer in the yaml file we get the same error.
We will try to update matchbox to the latest version.

**Comment by TristanKEREVAL** [comment]
We can close the issue for now and I will reopen it later if this still doesn't work with the latest version

**Comment by oliveregger** [comment]
thanks! then we just leave it open ... let me know when you updated if we can close it or have to check further

**Comment by TristanKEREVAL** [comment]
Hello, the problem is solved with the latest version of matchbox ! Thank you !
