### ISSUE TITLE
Problem with DocumentReference.mime type validation with a FTS 

### ISSUE THREAD

**Issue by TristanKEREVAL** [ahdis/matchbox#224]
We have encountered a problem with the validation of DocumentReference ressources using our terminology server (https://smt.esante.gouv.fr/fhir/), the matchbox validator (v3.5.3) returns an error for the DocumentReference.content[0].attachment.contentType attributes: 
![image](https://github.com/ahdis/matchbox/assets/122813625/8440f8b4-cc9d-4e82-be72-84c271dff3ef)

We then tried with the https://tx.fhir.org/ terminology server, and with this configuration we get no error, BUT there is no validation of the code. We get no error even with an incorrect code.
Here's an example using the incorrect code : "text/erreur", and the validation do not return any error.
[documentreference-example.json](https://github.com/ahdis/matchbox/files/15063697/documentreference-example.json)
 
The problem might be due to the terminology servers, but it seems that hapi fhir developed a hack : https://github.com/hapifhir/hapi-fhir/issues/5634
Is it a known mechanism and is it normal ?
Thanks

**Comment by oliveregger** [comment]
a) looks like there is no validation capability of your teminology server for bcp:13 (this might be, because it is not a finite list of mime-types)
b) hapi-fhir might have some special code handling for bcp13, but this is not relevant to the matchbox code

@TristanKEREVAL can you update to the latest version? the terminology support has been greatly improved in the last versions of the core libraries, not sure if this will help for that specific problem but would be easier to test and track down

**Comment by TristanKEREVAL** [comment]
Thank you for your answer. 
We tried to validate with the latest Matchbox version (3.8.1) but there is still no code verification with the tx.fhir.org fts.

**Comment by qligier** [comment]
Hi @TristanKEREVAL! `text/erreur` is a valid code according to both BCP-13 and http://hl7.org/fhir/ValueSet/mimetypes.
What would you expect here as a result?

**Comment by TristanKEREVAL** [comment]
Hi @qligier , i tried to "expand" this ValueSet but could not get the list of possible value (probably linked to the fact it is not a finite list of possible value). So I tried with this code thinking it would not exist.
If I try with a random series of letter like : 
        "contentType": "text/erreur123433333333333333333333333",
I still get no code validation, and I would expect a error message about the non presence of this code in the binded VS.
Thanks.

**Comment by qligier** [comment]
> i tried to "expand" this ValueSet but could not get the list of possible value (probably linked to the fact it is not a finite list of possible value).

Sure, it won't be possible to expand an infinite list of codes.

> So I tried with this code thinking it would not exist. If I try with a random series of letter like : "contentType": "text/erreur123433333333333333333333333", I still get no code validation, and I would expect a error message about the non presence of this code in the binded VS. Thanks.

So you have bound another value set than http://hl7.org/fhir/ValueSet/mimetypes to that field?
Can we see the profile somewhere?

**Comment by TristanKEREVAL** [comment]
We did not change the binding, but as seen here : https://www.hl7.org/fhir/R4/datatypes.html#attachment.
The binding to this VS is required, so we wanted to test the validation of the code coming from this VS.
But maybe, with the infinite nature of this ValueSet, the validation is not possible.

**Comment by qligier** [comment]
I would say that it is working as expected:

- http://hl7.org/fhir/ValueSet/mimetypes contains all codes that are valid according to BCP-13 (okay, it's not infinity, but the number is huge)
- `text/erreur123433333333333333333333333` is valid according to BCP-13
- `text/erreur123433333333333333333333333` is then present in http://hl7.org/fhir/ValueSet/mimetypes.
- Your document is then valid on that point.
- `text/erreur123433333333333333333333333` is not registered within IANA, but that is not important and does not change the validity of the media type.

If you want to test the validator on that point, you have to use a code that is not BCP-13 compliant:
``` 
     type-name = restricted-name
     subtype-name = restricted-name

     restricted-name = restricted-name-first *126restricted-name-chars
     restricted-name-first  = ALPHA / DIGIT
     restricted-name-chars  = ALPHA / DIGIT / "!" / "#" /
                              "$" / "&" / "-" / "^" / "_"
     restricted-name-chars =/ "." ; Characters before first dot always
                                  ; specify a facet name
     restricted-name-chars =/ "+" ; Characters after last plus always
                                  ; specify a structured syntax suffix
```

Values like `kereval/@invalid` should be rejected (because '@' is not a valid character).
