### ISSUE TITLE
Validation: CapabilityStatement is cached forever

### ISSUE THREAD

**Issue by oliveregger** [ahdis/matchbox#43]
When new Profiles (StructuredDefinition) are uploaded they are not visible afterwards in supportedProfile. E.g. after upload IPS ig the Bundle-uv-ips profile is not visible.

https://test.ahdis.ch/matchbox/#/CapabilityStatement
https://gazelle.ihe.net/matchbox/#/CapabilityStatement

```json
"profile": "http://hl7.org/fhir/StructureDefinition/Bundle",
          "supportedProfile": [
...
            "http://hl7.org/fhir/uv/ips/StructureDefinition/Bundle-uv-ips",
```

After a restart of the server it is shown. Validation depends on this information for the Dropdown box against which to validate.

**Comment by skbhaskarla** [comment]
@oliveregger, I think I ran into this type of issue before. I investigated the cause and found some settings in the application.yaml file were causing some issues with caching. I suggest the following changes to see if this solves your issue:
    [retain_cached_searches_mins: 0](https://github.com/ahdis/matchbox/blob/c8de7e1e71266d9aecc4a66f063b3376a7198d01/src/main/resources/application.yaml#L61)
and
[reuse_cached_search_results_millis: 0](https://github.com/ahdis/matchbox/blob/c8de7e1e71266d9aecc4a66f063b3376a7198d01/src/main/resources/application.yaml#L62)

**Comment by oliveregger** [comment]
@skbhaskarla wow thanks, we will check, cc @unixoid

**Comment by skbhaskarla** [comment]
In addition to my previous comment, please see this documentation link: 
6.4.1 Search Result Caching
https://hapifhir.io/hapi-fhir/docs/server_jpa/configuration.html

**Comment by unixoid** [comment]
Findings:

- Configuration parameters mentioned above do not seem to have a direct influence on the problem, as they control caching of search results and not of capability statements.
- The class org.hl7.fhir.common.hapi.validation.support.CachingValidationSupport uses a wrong cache configuration.  We were unable to determine what exactly is wrong there, but this is why we use  ch.ahdis.fhir.hapi.jpa.validation.CachingValidationSupport instead.
- This is relevant because ca.uhn.fhir.rest.server.provider.ServerCapabilityStatementProvider creates capability statements based on the contents of its IValidationSupport bean.
- ca.uhn.fhir.rest.server.method.ConformanceMethodBinding has its own cache.
- Two IValidationSupport instances were actually created in the project --- one in ca.uhn.fhir.jpa.starter.FhirServerConfigR4 (the right one, but not as a Spring bean), and one in ca.uhn.fhir.jpa.starter.StarterJpaConfig (the wrong one, but as a Spring bean).  Changed as follows: the first one promoted to a Spring bean, the second one removed.  
- Using a non-cached implementation of IValidationSupport helps as well.

**Comment by unixoid** [comment]
@oliveregger Please decide whether this issue can be closed.

**Comment by oliveregger** [comment]
thx a lot! for the next time could you create a Pull Request instead of a commit and describe the changes in changelog.md?
